---
- name: Grading playbook for SCENARIO_HTTPD
  hosts: satellite
  become: True
  gather_facts: yes
  tasks:

    - name: Checking the status of the Satellite service using hammer ping
      ansible.builtin.command: "hammer ping"
      register: hammer_result
      changed_when: false
      ignore_errors: true

    - name: Search for SSL error in log file
      ansible.builtin.command: "grep -F 'SSL Library Error: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match' /var/log/httpd/foreman-ssl_error_ssl.log"
      register: ssl_error
      changed_when: false
      ignore_errors: true

    - name: Checking result
      debug:
        msg: "Success. your alphanumeric code for completion is HTTPD615"
      when: ssl_error.rc == 0 and hammer_result.rc == 0

    - name: In case of failure
      debug:
        msg: "Please try again"
      when: ssl_error.rc != 0 or hammer_result.rc != 0

